情報の多い：発生・集中＝年齢（17段階）*原単位（推定に誤差あると仮定）
情報の少ない：発生・集中＝年齢（17段階）*原単位（推定に誤差あると仮定）


未来のOD = 現在OD　*（発生・集中変化）

In [9]:
import pandas as pd

In [10]:
intensity = pd.read_csv('../Workshop-data/東京PT原単位.csv', encoding="shift-jis")
intensity = intensity[intensity['居住地']== '1680_合計']

In [12]:
good_intensity = intensity.copy()
bad_in

       調査年      居住地       年齢階層    居住人口    外出人口    外出率   トリップ数  グロス原単位  ネット原単位
324  平成３０年  1680_合計    01_5〜9歳   17280   16848  0.975   42336   2.450   2.513
325  平成３０年  1680_合計  02_10〜14歳   19236   18660  0.970   45400   2.360   2.433
326  平成３０年  1680_合計  03_15〜19歳   19588   17766  0.907   39406   2.012   2.218
327  平成３０年  1680_合計  04_20〜24歳   22472   17291  0.769   39958   1.778   2.311
328  平成３０年  1680_合計  05_25〜29歳   20553   15721  0.765   34995   1.703   2.226
329  平成３０年  1680_合計  06_30〜34歳   24877   20406  0.820   54089   2.174   2.651
330  平成３０年  1680_合計  07_35〜39歳   30859   23755  0.770   60142   1.949   2.532
331  平成３０年  1680_合計  08_40〜44歳   35137   27941  0.795   77881   2.216   2.787
332  平成３０年  1680_合計  09_45〜49歳   35756   26900  0.752   68849   1.926   2.559
333  平成３０年  1680_合計  10_50〜54歳   26533   20984  0.791   56544   2.131   2.695
334  平成３０年  1680_合計  11_55〜59歳   19797   15209  0.768   39073   1.974   2.569
335  平成３０年  1680_合計  12_60〜64歳   24967   18824  0.754   49397   1.978   2.624
336  平成３０年  1680_合計  13_65〜69歳   28651   19494  0.680   54626   1.907   2.802
337  平成３０年  1680_合計  14_70〜74歳   30134   20494  0.680   56937   1.889   2.778
338  平成３０年  1680_合計  15_75〜79歳   25220   15434  0.612   43141   1.711   2.795
339  平成３０年  1680_合計  16_80〜84歳   13633    8372  0.614   24630   1.807   2.942
340  平成３０年  1680_合計    17_85歳〜   13699    5907  0.431   15202   1.110   2.574
341  平成３０年  1680_合計      18_合計  408392  310006  0.759  802606   1.965   2.589